name = "FFMPEG"
uuid = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
authors = ["SimonDanisch <sdanisch@gmail.com>"]
version = "0.2.2"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
